[package]
name = "ether-dream-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ether-dream-dac-emulator = "0.3.0"
futures = "0.3"
smol = "0.1"
nannou = "0.17.1"